/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:a9cc522b-be5e-47a6-832a-6f0f539a5b98",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_Ti6NX1WuU",
    "aws_user_pools_web_client_id": "628m9db77ngch06ps4k2ik8ent",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://uwpoxledpjg3jpb6gqoynhvrn4.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-q5wmrowhzfbijjmmzqjt4mkpsa"
};


export default awsmobile;
